name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

permissions:
  actions: write
  id-token: write
  contents: write

jobs:
  precheck:
    name: Precheck
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        id: vars
        shell: bash
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo ${{ github.event.inputs.version }} > VERSION
          git add VERSION
          sed -i -e "s/^\:project-version\:\ .*/:project-version: ${{ github.event.inputs.version }}/g" README.adoc
          git config --global user.email "${{ secrets.COMMIT_EMAIL }}"
          git config --global user.name "Steve Lorello"
          git commit -a -m "Releasing version ${{ github.event.inputs.version }}"
          git push origin main
  universal-build:
    name: Universal Build
    needs: [ precheck ]
    uses: slorello89/redis-smart-cache-cli/.github/workflows/universal.yml@main
    with:
      project-version: ${{ needs.precheck.outputs.version }}
  native-build:
    name: Native Build
    needs: [precheck]
    uses: slorello89/redis-smart-cache-cli/.github/workflows/native-build.yml@main
    with:
      project-version: ${{ needs.precheck.outputs.version }}
  release:
    name: Release
    needs: [precheck, universal-build, native-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Download universal
        uses: actions/download-artifact@v3
        with:
          name: universal
      - run: ls -l
      - name: Release
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ secrets.JRELEASER_DOCKER_PASSWORD }}